### ISSUE TITLE
Question about Qoala-T score

### ISSUE THREAD

**Issue by jlegault** [Qoala-T/QC#19]
Hi all,

Our lab is interested in using Qoala-T for all our stuctural neuroimaging data that we are currently analyzing.  I was able to run all our subject's data through the part A. Predicting scan Qoala-T score by using Braintime model very easily.  However, the output shows that a majority of the data should undergo QC checks.  

I was wondering if the Qoala-T score gives any information towards which kind(s) of errors may exist in the data (e.g. in the .csv file you all create/use for manual QC, you all separate these into errors in movement, temporal lobe missing, etc..).  I would like to train undergrad RAs to help with this process and it would be great if Qoala-T could provide some output suggesting which kinds of Freesurfer edits should be conducted.  Is this at all available?

Best,

Jen

**Comment by larawierenga** [comment]
Hi Jen,

We are happy to hear Qoala-T is useful for your dataset. We did indeed aimed to test whether we would be able to predict the different kinds of errors (e.g. temporal poles, pial etc). However, the accuracies were not in a range that was useful. Nevertheless, we did include it in the manual QC file, as we thought is was a helpful guideline to get more structure in the manual rating process. In addition, you may want tot decide not to include some regions for further analyse. E.g. we noted a lot of errors in the temporal poles, as such we do not analyse this region.

In addition, note that given the increasing size of datasets and subjectivity of editing, we decided not to edit the scans.

I hope this is helpful, let us know when you have any further questions. 

Best regards,
Lara
