### ISSUE TITLE
Changed stats2table.R script to make it work

### ISSUE THREAD

**Issue by helenahartmann** [Qoala-T/QC#28]
I had some issues with the for loop of the main function in line 112 where it says "for (x in 1:length(subjectDirs)){" --> changing x to 1 worked for me! could you explain why you put the 0?

**Comment by larawierenga** [comment]
Thanks Helena for catching this error! Starting at 0 gives to many directories, and for some reason wasn't caught before.

**Comment by helenahartmann** [comment]
You're welcome (took me a while to find out though haha)!
