### ISSUE TITLE
Freesurfer longitudinal

### ISSUE THREAD

**Issue by njudd** [Qoala-T/QC#8]
With the BrainTime dataset did you QC all time-points in the longitudinal stream?

**Comment by eduardklap** [comment]
Hi, our assumption is that scan quality is something that can vary substantially within persons between time-points, so for the scan quality calculations we used the cross-sectional outputs. This is also important for the Qoala-T model, as the surface holes (which is the most predictive feature of scan quality) are only calculated in the cross-sectional parcellations (see aseg_stats files).
Hope this helps, drop a message if you need more information.

Best,
Eduard
